apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: model
spec:
  replicas: 1
  selector:
    matchLabels:
      component: model-layer
  template:
    metadata:
      labels:
        component: model-layer
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: sieve-ml-model
        image: htrivedi05/sieve-ml-model:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: model-layer-service
  namespace: model
spec:
  type: ClusterIP
  selector:
    component: model-layer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000