apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: celery-horizontal-pod-autoscaler
  namespace: sieve
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery-runner
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70